//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPRazorDBApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public int ID { get; set; }
        public string COMMON { get; set; }
        public string BOTANICAL { get; set; }
        public string ZONE { get; set; }
        public string LIGHT { get; set; }
        public string PRICE { get; set; }
        public string AVAILABILITY { get; set; }
    }
}
